# Generated by Django 2.1.3 on 2018-11-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181120_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
