# Generated by Django 2.1.3 on 2018-11-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default=2, upload_to='product_imgs'),
            preserve_default=False,
        ),
    ]
