# Generated by Django 2.1.3 on 2018-11-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20181120_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
